---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Install required packages
      apt:
        name:
          - systemd
          - python3
          - curl
          - ca-certificates
        state: present
      when: ansible_os_family == "Debian"

  roles:
    - role: traefik
      traefik_version: "3.1.7"
      traefik_service_enabled: true
      traefik_service_state: "started"