---
- name: Verify
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Check if traefik user exists
      user:
        name: traefik
        state: present
      check_mode: true
      register: user_check
      failed_when: user_check.changed

    - name: Check if traefik group exists
      group:
        name: traefik
        state: present
      check_mode: true
      register: group_check
      failed_when: group_check.changed

    - name: Verify traefik directories exist
      file:
        path: "{{ item }}"
        state: directory
      check_mode: true
      register: dir_check
      failed_when: dir_check.changed
      loop:
        - /opt/traefik
        - /etc/traefik
        - /var/lib/traefik
        - /var/log/traefik

    - name: Check if traefik binary is installed
      stat:
        path: /usr/local/bin/traefik
      register: binary_stat
      failed_when: not binary_stat.stat.exists

    - name: Verify traefik binary is executable
      file:
        path: /usr/local/bin/traefik
        mode: '0755'
      check_mode: true
      register: binary_perms
      failed_when: binary_perms.changed

    - name: Check traefik version
      command: /usr/local/bin/traefik version
      register: version_output
      changed_when: false
      failed_when: "'3.1.7' not in version_output.stdout"

    - name: Verify systemd service file exists
      stat:
        path: /etc/systemd/system/traefik.service
      register: service_file
      failed_when: not service_file.stat.exists

    - name: Check if traefik service is enabled
      systemd:
        name: traefik
        enabled: true
      check_mode: true
      register: service_enabled
      failed_when: service_enabled.changed

    - name: Check if traefik service is running
      systemd:
        name: traefik
        state: started
      check_mode: true
      register: service_running
      failed_when: service_running.changed

    - name: Verify traefik service status
      command: systemctl is-active traefik
      register: service_status
      changed_when: false
      failed_when: service_status.stdout != "active"

    - name: Verify traefik.yaml configuration file exists
      stat:
        path: /etc/traefik/traefik.yaml
      register: config_file
      failed_when: not config_file.stat.exists

    - name: Verify traefik.yaml has correct ownership
      file:
        path: /etc/traefik/traefik.yaml
        owner: traefik
        group: traefik
        mode: '0644'
      check_mode: true
      register: config_perms
      failed_when: config_perms.changed

    - name: Wait for traefik to be fully started
      wait_for:
        port: 8080
        host: "127.0.0.1"
        timeout: 30
      ignore_errors: true
      register: api_port_check

    - name: Test traefik API dashboard accessibility (insecure mode)
      uri:
        url: "http://127.0.0.1:8080/api/overview"
        method: GET
        status_code: 200
      register: api_response
      when: 
        - api_port_check is succeeded
        - traefik_api_insecure | default(true) | bool
      ignore_errors: true

    - name: Test traefik dashboard web interface (insecure mode)
      uri:
        url: "http://127.0.0.1:8080/dashboard/"
        method: GET
        status_code: 200
      register: dashboard_response
      when: 
        - api_port_check is succeeded
        - traefik_api_insecure | default(true) | bool
      ignore_errors: true

    - name: Verify traefik is listening on web entrypoint
      wait_for:
        port: 80
        host: "0.0.0.0"
        timeout: 10
      ignore_errors: true
      register: web_port_check

    - name: Verify traefik is listening on websecure entrypoint
      wait_for:
        port: 443
        host: "0.0.0.0"
        timeout: 10
      ignore_errors: true
      register: websecure_port_check

    - name: Display connectivity test results
      debug:
        msg:
          - "API Port (8080): {{ 'PASS' if api_port_check is succeeded else 'FAIL' }}"
          - "Web Port (80): {{ 'PASS' if web_port_check is succeeded else 'FAIL' }}"
          - "WebSecure Port (443): {{ 'PASS' if websecure_port_check is succeeded else 'FAIL' }}"
          - "API Dashboard: {{ 'PASS' if api_response is succeeded else 'SKIP' if not (traefik_api_insecure | default(true) | bool) else 'FAIL' }}"
          - "Dashboard Web Interface: {{ 'PASS' if dashboard_response is succeeded else 'SKIP' if not (traefik_api_insecure | default(true) | bool) else 'FAIL' }}"